### ISSUE TITLE
Set up Emacs-Kotlin-Mode-Maintainers/Emacs-Kotlin-Mode

### ISSUE THREAD

**Issue by russel** [gregghz/kotlin-mode#4]
I have set up the Emacs-Kotlin-Mode-Maintainers organization and invited @gregghz to be an owner. I propose transferring this repository to that organization so that this mode can have many people responsible and so avoid any "under a bus" type scenarios.

Currently this repository is in MELPA so there would need to be a change made to the MELPA recipe after this above action if taken.

**Comment by gregghz** [comment]
Thanks for doing this. Any chance we could go with a simpler name like
kemacs or emacsk? If I'm not mistaken (and I might be) the name of the org
is in the URL of the repo and I'd prefer it to be simpler. Also I would
suspect we'd want the org to be (long term) focused in kotlin tools in
emacs in general and not restricted to the major mode.

**Comment by russel** [comment]
kemacs and emacsk do not work for me as the implication is some form of emacs variant rather than add ons. I can definitely go with removing the Mode if we are indeed to have things other than the major mode. We could go with Folk rather than Maintainers. I have three other Emacs bits projects and organization name has never been a problem. The repository names are perhaps potentially more of a problem, but once cloned I have never had issues with longish names.

**Comment by gregghz** [comment]
yep, don't mean to imply a new spin on emacs :)

How about "kotlin-emacs"? I don't know. I just don't love a long name with capitals and dashes. Granted, the name is a pretty minor issue.

**Comment by russel** [comment]
@gregghz I guess we should close the debate here and open an issue on the now established organization and mainline? I believe there are now three owners of the organization, the thwo of us and @quantumman

**Comment by gregghz** [comment]
I'll close this. No need for further debate, I've come to terms with the
name :) in the event that we want to work on things beyond kotlin-mode, we
can discuss the name again.

**Comment by russel** [comment]
That works for me!

Please do open the debate if the name becomes a problem, I am sure a compromise is achievable. But for now we have a status quo.
